name: Run Ansible playbook (with AWS support)
author: Mauro Torrez
description: Run Ansible playbook

branding:
  icon: server
  color: gray-dark

inputs:
  playbook:
    description: Name of the playbook to execute.
    required: yes
  arguments:
    description: Extra arguments for the playbook.
    required: no
  extra_vars_yaml:
    description: Extra variables for the playbook in YAML syntax.
    required: no
  working_directory:
    description: Working directory.
    required: no
  aws_access_key_id:
    description: AWS Access Key ID.
    required: no
  aws_secret_access_key:
    description: AWS Secret Access Key.
    required: no
  aws_session_token:
    description: AWS Session Token
    required: no
  aws_region:
    description: AWS Region, e.g. us-east-1
    required: no

outputs:
  command:
    description: Command to be executed.

runs:
  using: 'docker'
  image: 'Dockerfile'
